 SELECT a.business_id,
    btrim(a.name, '"'::text) AS name,
    a.categories,
    a.attributes,
    a.hours,
    a.stars,
    a.review_count,
    a.is_open,
    a.longitude,
    a.latitude,
    a.address,
    a.city,
    a.postal_code,
    a.neighborhood,
    b._id,
    b.facility_name,
    b.encounter,
    b.id,
    b.placard_st,
    b.bus_st_date,
    b.inspect_dt,
    b.start_time,
    b.end_time,
    b.description,
    (b.num || ' '::text) || b.street AS b_address,
    b.city AS b_city,
    b.rating,
    b.description_new,
    b.low,
    b.medium,
    b.high
   FROM restaurants a
     JOIN violations b ON levenshtein(btrim(a.name, '"'::text), b.facility_name) < 3 AND btrim(a.postal_code) = btrim(b.zip) AND levenshtein(a.address, (b.num || ' '::text) || b.street) < 4;
