 SELECT a.business_id,
    a.name,
    a.address,
    a.postal_code,
    a.neighborhood,
    a.latitude,
    a.longitude,
    a.categories,
    a.attributes,
    a.is_open,
    a.review_count,
    a.hours,
    a.stars,
    b.establishment_id,
    b.establishment_name,
    b.establishment_address,
    b.inspection_date,
    b.last_inspection,
    b.count_minor,
    b.count_signficant,
    b.count_crucial,
    b.count_na,
    b.total_count_cs,
    c.review_id,
    c.user_id,
    c.stars AS review_stars,
    c.review_text,
    c.useful,
    c.funny,
    c.cool,
    c.date AS review_date
   FROM restaurants a
     JOIN toronto_inspections b ON levenshtein(upper(btrim(a.name)), upper(btrim(b.establishment_name))) < 3 AND levenshtein(upper(btrim(a.address)), upper(btrim(b.establishment_address))) < 4
     JOIN toronto_reviews c ON a.business_id = c.business_id AND b.last_inspection < c.date AND b.inspection_date >= c.date;